### ISSUE TITLE
Update release in the Maven Central Repository

### ISSUE THREAD

**Issue by MrDOS** [NeuronRobotics/nrjavaserial#20]
The latest release of nrjavaserial in the Central Repository is [3.7.5.1](http://mvnrepository.com/artifact/com.neuronrobotics/nrjavaserial), which is quite out-of-date. It'd probably be good to get that updated to 3.9.3 (.4?). Is there any way I can go about doing that?

**Comment by crea-doo** [comment]
I also would be very happy to see a release to Maven central happen.
Therefore I've created a branch where the existing Ant build is fully replaced by Maven and some clean up was done (see https://github.com/crea-doo/nrjavaserial/tree/maven) - this also affects issue #29.

It uses the maven-release-plugin for performing the actual releases and also has the ability to release to Maven Central. Furthermore the bundle-maven-plugin is used to create OSGi compatible manifest entries. The Bundle-NativeCode entries are deliberately not used because the loading of native libs is already performed by the [NativeResource.java](../blob/master/nrjavaserial/src/main/java/gnu/io/NativeResource.java#L31).

Another thing I added is a configuration for Travis CI which runs the Maven build after every commit (see https://travis-ci.org/crea-doo/nrjavaserial)

I'm using here a configuration that I also use for releasing some other projects - an alternative may be the configuration discussed at http://central.sonatype.org/pages/apache-maven.html

Should I open a separate issue with a pull request for all the changes?

**Comment by TYoung86** [comment]
This is the most active branch of RxTx, and it's looking pretty righteous.

Kudos to you guys for keeping it maintained, and building on it as well.

It's a shame the setup in the central Maven is not sync'd up.

Looks like @crea-doo has the same feels.

All I can do is throw links, I think they're all reachable from the sonatype.org link @crea-doo mentioned.
http://central.sonatype.org/pages/producers.html
http://central.sonatype.org/pages/releasing-the-deployment.html
http://central.sonatype.org/pages/ossrh-guide.html

**Comment by andyrozman** [comment]
I maintain maven version of nrserial in my nexus repository... If you need it...

URL:
http://www.atech-software.com:8081/nexus/content/groups/public/

            <dependency>
                <groupId>com.neuronrobotics</groupId>
                <artifactId>nrjavaserial-j15</artifactId>
                <version>3.9.3.1</version>
            </dependency>

It is built against Java 1.5... and it contains all current changes.

**Comment by crea-doo** [comment]
This seems to work now as version 3.10.1 and 3.10.2 arte available via Maven Central now.

@TYoung86: Regarding the #19 I'll create a pull request. But it seems that now Gradly is now used as build system, so the configuration for the automated build has to be switched accordingly.
