### ISSUE TITLE
NRSerialPort should make RXTX port instance accessible to user

### ISSUE THREAD

**Issue by andyrozman** [NeuronRobotics/nrjavaserial#26]
Hi !
I started using nrjavaserial instead of vanilla Rxtx... I really like using NRSerialPort because it makes Rxtx easy usable (without need to set parameters, which are use default values), but for some devices I use, option to set specific values would be very welcome. 
If user could access underlaying RXTX instance this wouldnöät be a problem, but so far we donät have that option. Would it be possible to get this instance directly, or if you could implement needed methods:
- enableReceiveTimeout
- setSerialPortParams
- setDTR
- setRTS

I use a lot of serial devices in my application and about 90% are covered with default settings, but some require extra settings...

Take care,
Andy

**Comment by andyrozman** [comment]
I am not really Git friend, so this might be problematic for me to do, but I could share my change as source file, if this would be enough?

**Comment by madhephaestus** [comment]
sorry, but no, i only make additions if those additions are tracked to the user that made them through the git history. If i add the changes, in the git history it will look like they were my changes. 

Learning git workflow and project contributions is a necessary part of being a software engineer of any kind, i would highly suggest learning it.

**Comment by andyrozman** [comment]
Really? I am professional developer for about 15 years, and this time I could easily survive without knowing git workflow... I will learn it when I am required to by my employer (or customer if I decide to reopen my own company), and perhaps I will commit my change then...

**Comment by jason-s** [comment]
I wouldn't close this as won't fix, just keep it open until someone is willing to create a pull request.

side note;

>Learning git workflow and project contributions is a necessary part of being a software engineer of any kind, i would highly suggest learning it.

Helpful, but not necessary. I'm learning Git right now, only because I have no choice in a work project. Not knowing it has been a stumbling block for submitting changes to open-source projects (even simple ones like documentations) and IMHO GitHub should offer a feature to submit simple changes to one or more files using the web interface, and create the proper pull request behind the scenes, so that beginners can contribute without having to know the intricacies of Git, even if it's just to do a Github fork -> git clone -> git add -> git commit -> git push -> Github pull request.

**Comment by madhephaestus** [comment]
fair point

**Comment by MrDOS** [comment]
@andyrozman, if you could share your changes via [Gist](https://gist.github.com/), then someone else might be able to pick it up and finish the merge.

I'm in a similar boat to @madhephaestus – I don't really like to sign off on code I haven't written. If you send me an e-mail, though, I can try to walk you through creating a pull request if you would like.

**Comment by andyrozman** [comment]
@MrDOS ... I will contact you either this week or next one, so you can help me with this... I am currently in process of preparing my project to be sent to testers, before release, so I am little swamped, but it should be better in few days...

**Comment by andyrozman** [comment]
created pull request. I think this should be done now...

**Comment by andyrozman** [comment]
This was merged... I am closing it (if I can)...
